apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
      <h1>Hello from Edvinas</h1>
      </br>
      <h1>Deployment in {{ .Values.env.name }} using Helm Chart for Nord Security</h1>
    </html>
