apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Testing ConfigMap - Edvinas</title>
    </head>
    <body>
        <p>Hello world<p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: my-config
  namespace: default